import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Footer from "@/components/mainui/Footer";
import HeaderClient from "@/components/mainui/HeaderClient";
import { Toaster } from "sonner";
import FrontendQueryProvider from "@/context/FrontendQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Asset List App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="h-min-screen flex flex-col justify-between">
          <FrontendQueryProvider>
            <HeaderClient />
            {children}
            <Footer />
            <Toaster richColors position="top-right" className="z-50" />
          </FrontendQueryProvider>
        </div>
      </body>
    </html>
  );
}
