import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import DashLayout from "@/Layout/Dashlayout";
import ClientProviders from "@/context/ClientProviders";
import { Toaster } from "sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
          <ClientProviders>
            <DashLayout>
              {children}
            </DashLayout>
            <Toaster richColors position="top-right" className="z-50"/>
            
          </ClientProviders>
       
        
      </body>
    </html>
  );
}
